version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/QuackatronHQ/grafana"

[[transformers]]
name = "gofmt"